---
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studenti
    username: admin
    password: admin

#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt:
  clientId: devmind-app
  client-secret: secret
  accessTokenValidititySeconds: 120
  refreshTokenValiditySeconds: 1000
