spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/studenti
    username: postgres
    password: postgres

server:
  port: 8081

jwt:
  cookieName: devmindApp
  secret: secret
  accessTokenValiditityMS: 360000